base_model = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.08386
output = 0.16772
cache_read = 0.016772

[limit]
context = 1_048_576
